 import important libraries 


In [2]:
import numpy as np 
import math

some important functions

In [17]:
# create weight and bias matrices 
def mate_me_out(input_shape, output_shape, weight_shape_m):
    # initializing weights matrix 
    empty_w = []
    for layer in range(weight_shape_m.shape[0]):
        if layer == 0: 
            empty_w.append(np.random.random([input_shape[0], weight_shape_m[layer]]))
        else:
            empty_w.append(np.random.random([weight_shape_m[layer-1], weight_shape_m[layer]]))
    empty_w.append(np.random.random([weight_shape_m[-1], output_shape[0]]))
    empty_w = np.array(empty_w, dtype=object)

    empty_b = [] 
    for layer in range(weight_shape_m.shape[0]): 
        empty_b.append(np.random.random([weight_shape_m[layer]])) # initializing bias matrix 
    empty_b.append(np.random.random([output_shape[0]]))
    empty_b = np.array(empty_b, dtype=object)

    print('weight matrix consists of ', empty_w.shape[0], 'layers\n and bias matrix\' shape is: ', empty_b.shape[0])

    return empty_w, empty_b

def forward_propagation(x, w, b): 
    weighted_layers = [] 
    for layer in range(len(w)):
        print(layer)
        if layer == 0: 
            weighted_layers.append(np.dot(x, w[layer]) + b[layer])
        else: 
            weighted_layers.append(np.dot(weighted_layers[layer-1], w[layer]) + b[layer])
    weighted_layers = np.array(weighted_layers, dtype=object)
 
    return weighted_layers
     


    

input, output, weights and biases matrices 

In [18]:
inputm = np.array([1, 3, 5])
input_shape = inputm.shape
print('input matrix is of shape: ', input_shape)
outputm = np.array([3, 4])
output_shape = outputm.shape
print('output matrix is of shape:', output_shape)
layers_shape = np.array([4, 5, 3]) #first, let's make it simplistic 
layers_shape_shape = layers_shape.shape
weights_m, bias_m = mate_me_out(input_shape, output_shape, layers_shape)
# now let us do forward propagation 
weighted_layers = forward_propagation(inputm, weights_m, bias_m)
print(weighted_layers, weighted_layers.shape)
 


input matrix is of shape:  (3,)
output matrix is of shape: (2,)
weight matrix consists of  4 layers
 and bias matrix' shape is:  4
0
1
2
3
[array([3.83364443, 2.21962428, 4.26261996, 3.94467996])
 array([ 6.17736473,  8.46811102, 11.40097981,  9.59007839,  8.12307769])
 array([23.11086407, 13.21565747, 16.47741818])
 array([28.21712462, 24.96122952])] (4,)


defining a function to create weights

strarting the simple calculation

In [5]:
weight_1 = np.random.random([input_shape[0], layers_shape[0]]).T
bias_1 = np.random.random([layers_shape[0], 1]).T
print(weight_1)
print(bias_1)
output_of_first_layer = np.sum(inputm*weight_1, axis=1)+bias_1
print(output_of_first_layer)

[[0.19364728 0.04211219 0.22314228]
 [0.67595247 0.05875658 0.51221964]
 [0.43418752 0.10842454 0.88484599]
 [0.02494606 0.73459086 0.82755451]]
[[0.23290069 0.37405417 0.98629779 0.97468476]]
[[1.66859595 3.78737459 6.1699889  7.34117594]]
